remote_theme: just-the-docs/just-the-docs
title: QRadar app framework version 2 documentation
description: QRadar app framework v2 documentation
repository: IBMSecurityDocs/qradar_appfw_v2
exclude: [scripts, templates, README.md, README.public.md, STYLE_GUIDE.md, Makefile, lint-rules.json, Gemfile*]
include: [docs, docs/*, index.md]
